### PR TITLE
support jumping to step definitions that don't use brackets

### PR DESCRIPTION
**Pull request by stan3**

### CODE REVIEW

**Comment by cdmwebs** [comment]
@superchris can you take a look here?

**Comment by dkarter** [comment]
Is this project no longer maintained?

**Comment by vveliev** [comment]
should we move to @stan3  fork !?

**Comment by superchris** [comment]
Hey, sorry for letting this fall of my radar so many times. I'm not using this package anymore myself, but I've merge this PR and published a new version of the package. If there's a way to transfer ownership of Atom packages, and you want to own it @stan3 I will be happy to do that.

**Comment by stan3** [comment]
sure, can do that

**Pull request merged**
